//Actions constants
const GET_INGREDIENTS = 'GET_INGREDIENTS';
const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
const GET_INGREDIENTS_FAILURE = 'GET_INGREDIENTS_FAILURE';

const GET_INGREDIENT_DETAILS = 'GET_INGREDIENT_DETAILS';
const DELETE_INGREDIENT_DETAILS = 'DELETE_INGREDIENT_DETAILS';

const GET_ORDER_STATUS = 'GET_ORDER_STATUS';
const GET_ORDER_STATUS_SUCCESS = 'GET_ORDER_STATUS_SUCCESS';
const GET_ORDER_STATUS_FAILURE = 'GET_ORDER_STATUS_FAILURE';
const CLEAR_ORDER_STATUS = 'CLEAR_ORDER_STATUS';

const PUT_BURGER_BUN = 'PUT_BURGER_BUN';
const PUT_BURGER_FILLING = 'PUT_BURGER_FILLING';
const REPLACE_BURGER_BUN = 'REPLACE_BURGER_BUN';
const DELETE_BURGER_FILLING = 'DELETE_BURGER_FILLING';
const REPLACE_BURGER_FILLING = 'REPLACE_BURGER_FILLING';

export {
  GET_INGREDIENTS,
  GET_INGREDIENTS_SUCCESS,
  GET_INGREDIENTS_FAILURE,
  GET_INGREDIENT_DETAILS,
  DELETE_INGREDIENT_DETAILS,
  GET_ORDER_STATUS,
  GET_ORDER_STATUS_SUCCESS,
  GET_ORDER_STATUS_FAILURE,
  CLEAR_ORDER_STATUS,
  PUT_BURGER_BUN,
  PUT_BURGER_FILLING,
  REPLACE_BURGER_BUN,
  DELETE_BURGER_FILLING,
  REPLACE_BURGER_FILLING,
};
